### ISSUE TITLE
TypeError: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by yoavram** [wooey/Wooey#102]
I install django 1.8.4, then `pip install -r requirements.txt` (requirements file from github) and `pip install wooey`, then I run `wooify -p test` and get this error:
```
Traceback (most recent call last):
  File "d:\anaconda3\envs\wooey\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\anaconda3\envs\wooey\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Anaconda3\envs\wooey\Scripts\wooify.exe\__main__.py", line 9, in <module>
  File "d:\anaconda3\envs\wooey\lib\site-packages\wooey\backend\command_line.py", line 50, in bootstrap
    subprocess.call(admin_command, **admin_kwargs)
  File "d:\anaconda3\envs\wooey\lib\subprocess.py", line 537, in call
    with Popen(*popenargs, **kwargs) as p:
  File "d:\anaconda3\envs\wooey\lib\subprocess.py", line 859, in __init__
    restore_signals, start_new_session)
  File "d:\anaconda3\envs\wooey\lib\subprocess.py", line 1086, in _execute_child
    args = list2cmdline(args)
  File "d:\anaconda3\envs\wooey\lib\subprocess.py", line 663, in list2cmdline
    needquote = (" " in arg) or ("\t" in arg) or not arg
TypeError: argument of type 'NoneType' is not iterable
```

Python 3.4.3, Win7 65bit, packages:
```
amqp                      1.4.8                     <pip>
anyjson                   0.3.3                     <pip>
billiard                  3.3.0.22                  <pip>
boto                      2.38.0                    <pip>
celery                    3.1.19                    <pip>
clinto                    0.1.2                     <pip>
coverage                  4.0.3                     <pip>
coveralls                 1.1                       <pip>
django                    1.8.4                    py34_0
django-autoslug           1.9.3                     <pip>
django-celery             3.1.17                    <pip>
django-storages-redux     1.3                       <pip>
docopt                    0.6.2                     <pip>
factory-boy               2.6.0                     <pip>
fake-factory              0.5.3                     <pip>
kombu                     3.0.32                    <pip>
msvc_runtime              1.0.1                    vc10_0  [vc10]
nose                      1.3.7                     <pip>
pip                       7.1.2                    py34_0
pluggy                    0.3.1                     <pip>
py                        1.4.31                    <pip>
python                    3.4.3                         5
pytz                      2015.7                    <pip>
requests                  2.9.1                     <pip>
setuptools                19.1.1                   py34_0
six                       1.10.0                    <pip>
tox                       2.3.1                     <pip>
virtualenv                13.1.2                    <pip>
wheel                     0.26.0                   py34_1
wooey                     0.9.1                     <pip>
```

**Comment by Chris7** [comment]
My bet is there is the 'which' command is failing to find django-admin.py. Can you verify this by providing the contents of 'admin_command' and 'admin_kwargs' on the script?

**Comment by yoavram** [comment]
I'm sorry, what do you mean by that? Should I add some print statements?
If so, which file and line?

**Comment by Chris7** [comment]
Yes, you can add a print statement right before:

d:\anaconda3\envs\wooey\lib\site-packages\wooey\backend\command_line.py

on line 50. Add this:

print(admin_command, admin_kwargs)

**Comment by yoavram** [comment]
Here's what it prints: https://gist.github.com/yoavram/79ee5b782de96bd1a648

**Comment by Chris7** [comment]
That's what I surmised, it cannot find django-admin.py. Could you confirm django-admin.py is on your PATH? As in, can you execute it from anyplace via django-admin.py (or do you need to do django-admin)?

**Comment by yoavram** [comment]
Yes it's in the path
```
D:> django-admin --version
1.8.4
```

**Comment by Chris7** [comment]
Thanks. It looks like we need to add a fallback check for 'django-admin'. Could you insert this piece of code after admin_path = which('django-admin.py') (line 45)

```
if admin_path is None:
    admin_path = which('django-admin')
```

Thank you again for your help and apologies for the inconveniences

**Comment by yoavram** [comment]
Sure, but so I need to import 'which' from somewhere?

**Comment by yoavram** [comment]
This doesn't work, because the which function doesn't find `django-admin`, as on Windows the file is called `django-admin.exe`.
I changed to:
```py
if admin_path is None:
    admin_path = which('django-admin.exe')
```
and it worked (but produced a new error).
