### ISSUE TITLE
Non-UTF-8 code in django-admin.exe but no encoding declared

### ISSUE THREAD

**Issue by yoavram** [wooey/Wooey#104]
Running `wooify -p test` produces:
```
  File "D:\Anaconda3\envs\wooey\Scripts\django-admin.exe", line 1
SyntaxError: Non-UTF-8 code starting with '\x90' in file D:\Anaconda3\envs\wooey\Scripts\django-admin.exe on line 1, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
Traceback (most recent call last):
  File "d:\anaconda3\envs\wooey\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\anaconda3\envs\wooey\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Anaconda3\envs\wooey\Scripts\wooify.exe\__main__.py", line 9, in <module>
  File "d:\anaconda3\envs\wooey\lib\site-packages\wooey\backend\command_line.py", line 81, in bootstrap
    with open(to_name, 'wb') as new_file:
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\workspace\\wooeytest\\test\\test\\.\\middleware.py'
```

Windows 7, 64bit, Python 3.4.3, Django 1.8.4, wooey 0.9.1.

**Comment by Chris7** [comment]
It's looking better. Because it's now finding a .exe, calling it as 'python django-admin.exe ...' is not a good idea. So I think the last change needed is changing:

admin_command = [sys.executable] if sys.executable else []

to:

admin_command = []

If that works, I'll incorporate some platform specific code to handle these two cases. I think we're almost there!

**Comment by yoavram** [comment]
OK, now I get a bunch of import errors:
```
λ wooify -p wooeytest
Traceback (most recent call last):
  File "d:\anaconda3\envs\wooey\lib\site-packages\django\apps\config.py", line 114, in create
    cls = getattr(mod, cls_name)
AttributeError: 'module' object has no attribute 'django'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "wooeytest\manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "d:\anaconda3\envs\wooey\lib\site-packages\django\core\management\__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "d:\anaconda3\envs\wooey\lib\site-packages\django\core\management\__init__.py", line 312, in execute
    django.setup()
  File "d:\anaconda3\envs\wooey\lib\site-packages\django\__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "d:\anaconda3\envs\wooey\lib\site-packages\django\apps\registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "d:\anaconda3\envs\wooey\lib\site-packages\django\apps\config.py", line 119, in create
    import_module(entry)
  File "d:\anaconda3\envs\wooey\lib\importlib\__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2224, in _find_and_load_unlocked
ImportError: No module named 'kombu.transport.django'
Traceback (most recent call last):
  File "d:\anaconda3\envs\wooey\lib\site-packages\django\apps\config.py", line 114, in create
    cls = getattr(mod, cls_name)
AttributeError: 'module' object has no attribute 'django'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "wooeytest\manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "d:\anaconda3\envs\wooey\lib\site-packages\django\core\management\__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "d:\anaconda3\envs\wooey\lib\site-packages\django\core\management\__init__.py", line 312, in execute
    django.setup()
  File "d:\anaconda3\envs\wooey\lib\site-packages\django\__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "d:\anaconda3\envs\wooey\lib\site-packages\django\apps\registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "d:\anaconda3\envs\wooey\lib\site-packages\django\apps\config.py", line 119, in create
    import_module(entry)
  File "d:\anaconda3\envs\wooey\lib\importlib\__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2224, in _find_and_load_unlocked
ImportError: No module named 'kombu.transport.django'
Traceback (most recent call last):
  File "d:\anaconda3\envs\wooey\lib\site-packages\django\apps\config.py", line 114, in create
    cls = getattr(mod, cls_name)
AttributeError: 'module' object has no attribute 'django'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "wooeytest\manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "d:\anaconda3\envs\wooey\lib\site-packages\django\core\management\__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "d:\anaconda3\envs\wooey\lib\site-packages\django\core\management\__init__.py", line 312, in execute
    django.setup()
  File "d:\anaconda3\envs\wooey\lib\site-packages\django\__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "d:\anaconda3\envs\wooey\lib\site-packages\django\apps\registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "d:\anaconda3\envs\wooey\lib\site-packages\django\apps\config.py", line 119, in create
    import_module(entry)
  File "d:\anaconda3\envs\wooey\lib\importlib\__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2224, in _find_and_load_unlocked
ImportError: No module named 'kombu.transport.django'
Please enter the project directory wooeytest, and run python manage.py createsuperuser and python manage.py runserver to start. The admin can be found at localhost:8000/admin. You may also want to set your DJANGO_SETTINGS_MODULE environment variable to wooeytest.settings
```

**Comment by Chris7** [comment]
How did you install wooey? Kombu is a dependency that should be bundled in with celery/django-celery.

**Comment by yoavram** [comment]
kombu is installed, I did `pip install -r requirements.txt` on the requirements.txt file in the wooey repo:
```
λ python -c "import kombu; print(kombu.__version__)"
3.0.32
```
There is even a kombu.transport module, but not kombu.transport.django:
```
[wooey] D:\workspace\wooeytest
λ python -c "import kombu.transport"

[wooey] D:\workspace\wooeytest
λ python -c "import kombu.transport.django"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named 'kombu.transport.django'
```

**Comment by Chris7** [comment]
Ok. So you did not install from pip? You cloned the repo then installed it? Did you do 'pip install .' for wooey as well? It's odd because we never import kombu -- that is imported by a dependency.

**Comment by Chris7** [comment]
Here is a similar traceback on my machine:

```
>>> import kombu
>>> import kombu.transport
>>> import kombu.transport.django
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/chris/.virtualenvs/wooey/local/lib/python2.7/site-packages/kombu/transport/django/__init__.py", line 29, in <module>
    getattr(settings, 'DJKOMBU_POLLING_INTERVAL', 5.0))
  File "/home/chris/.virtualenvs/wooey/local/lib/python2.7/site-packages/django/conf/__init__.py", line 55, in __getattr__
    self._setup(name)
  File "/home/chris/.virtualenvs/wooey/local/lib/python2.7/site-packages/django/conf/__init__.py", line 41, in _setup
    % (desc, ENVIRONMENT_VARIABLE))
django.core.exceptions.ImproperlyConfigured: Requested setting DJKOMBU_POLLING_INTERVAL, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings
>>> kombu.VERSION
version_info_t(major=3, minor=0, micro=32, releaselevel='', serial='')
```

The Django traceback you can ignore, but I have 3.0.32 on Ubuntu and kombu.transport.django is valid.

**Comment by yoavram** [comment]
I downloaded the requirements file from github, then did:
```
conda create -n wooey python=3.4 -y
activate wooey
pip install django==1.8
pip install -r requirements.txt
pip install wooey
```

(`conda create` creates a virtual env, i installed django 1.8 because #103)

Maybe on Windows kombu doesn't install kombu.transport.django?

**Comment by Chris7** [comment]
I'm going to try and get on a windows machine to figure this out.

**Comment by yoavram** [comment]
You can get a windows VM here: https://dev.windows.com/en-us/microsoft-edge/tools/vms/windows/

**Comment by Chris7** [comment]
That is amazing. Thanks

**Comment by Chris7** [comment]
Installed miniconda:

```
conda create -n wooey python
activate wooey
pip install wooey
pip install Django==1.8.*
wooify -p test_project
```

I encountered that issue with kombu missing django. The release of kombu 3.0.32 is broken in some way. Install 3.0.31 to fix this.

**Comment by yoavram** [comment]
Yes, that solves it. I wonder if there is a way to avoid using 3.0.32? Probably in `setup.py`?

Now I get this:
```
λ wooify -p wooeytest
Traceback (most recent call last):
  File "d:\anaconda3\envs\wooey\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\anaconda3\envs\wooey\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Anaconda3\envs\wooey\Scripts\wooify.exe\__main__.py", line 9, in <module>
  File "d:\anaconda3\envs\wooey\lib\site-packages\wooey\backend\command_line.py", line 52, in bootstrap
    subprocess.call(admin_command, **admin_kwargs)
  File "d:\anaconda3\envs\wooey\lib\subprocess.py", line 537, in call
    with Popen(*popenargs, **kwargs) as p:
  File "d:\anaconda3\envs\wooey\lib\subprocess.py", line 859, in __init__
    restore_signals, start_new_session)
  File "d:\anaconda3\envs\wooey\lib\subprocess.py", line 1112, in _execute_child
    startupinfo)
OSError: [WinError 193] %1 is not a valid Win32 application
```

**Comment by Chris7** [comment]
Can you reinstall from the repo like:

pip install git+https://github.com/wooey/Wooey.git

I just tested this using Minoconda in a conda environment and was able to bootstrap the project and start it. The only caveat is that the windows dev vms are all x86 -- so I cannot test this on x64.

**Comment by Chris7** [comment]
For setup.py -- I think this there will be a release to fix it soon enough. If we get more reports of this error though, I'll lock in a dependency for the working version

**Comment by yoavram** [comment]
I had to `pip uninstall wooey` and then `pip install git+https://github.com/wooey/Wooey.git`.
`wooify -p testproject` then worked fine! Thanks!
Maybe you can just add a remark in `README.md`, something like "Note: kombu 3.0.32 gives errors"? Not everyone reports errors.
