### ISSUE TITLE
Add example scripts link to documentation

### ISSUE THREAD

**Issue by Chris7** [wooey/Wooey#131]
Add a link to this page:
https://github.com/wooey/Wooey/tree/master/wooey/tests/scripts

To give users some example scripts to start off with.

**Comment by arolling** [comment]
Hi, I ran into errors when trying to run the "without_args" sample script. It just waits eternally after you click Submit and the console where I have the server running returns:

`Internal Server Error: /scripts/no-arguments/
Traceback (most recent call last):
  File "C:\Users\rollinga\AppData\Local\Programs\Python\Python35-32\lib\site-packages\django\utils\datastructures.py", line 83, in __getitem__
    list_ = super(MultiValueDict, self).__getitem__(key)
KeyError: 'wooey_type'`

This also happened with another script I was trying to run without arguments, so it is reproducible.

**Comment by Chris7** [comment]
Hey @arolling 

I have a few questions for this:

Is {path} really in your traceback? Also, by wait -- do you mean the webpage hangs or doesn't update? Are there errors in the developer's console? And did you start the project with wooify?

**Comment by arolling** [comment]
Thanks @Chris7  for the quick response!

Yes, we started the project with wooify. I'm not sure what you mean by developer's console - the browser just stays on the webpage where you click "Submit" and that message (I replaced the file structure of my PC with {path} because i didn't think it was relevant) appears in the Command Prompt window where I am running the Django server (python manage.py runserver). The admin console for Wooey does not show it in the list of jobs. Here is the full traceback:
```
Internal Server Error: /scripts/no-arguments/
Traceback (most recent call last):
  File "C:\Users\rollinga\AppData\Local\Programs\Python\Python35-32\lib\site-packages\django\utils\datastructures.py", line 83, in __getitem__
    list_ = super(MultiValueDict, self).__getitem__(key)
KeyError: 'wooey_type'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\rollinga\AppData\Local\Programs\Python\Python35-32\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\rollinga\AppData\Local\Programs\Python\Python35-32\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\rollinga\AppData\Local\Programs\Python\Python35-32\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\rollinga\AppData\Local\Programs\Python\Python35-32\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\rollinga\AppData\Local\Programs\Python\Python35-32\lib\site-packages\wooey\views\views.py", line 160, in post
    data = super(WooeyScriptView, self).post(*args, **kwargs)
  File "C:\Users\rollinga\AppData\Local\Programs\Python\Python35-32\lib\site-packages\wooey\views\views.py", line 91, in post
    form = utils.get_master_form(pk=post['wooey_type'])
  File "C:\Users\rollinga\AppData\Local\Programs\Python\Python35-32\lib\site-packages\django\utils\datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
django.utils.datastructures.MultiValueDictKeyError: "'wooey_type'"
NoneType
[23/Jun/2016 09:14:46] "POST /scripts/no-arguments/ HTTP/1.1" 500 16687
```

As mentioned in my other issue, we are running with Wooey_Celery set to False, but other scripts with arguments do run successfully (like "choices").
