### ISSUE TITLE
'File Not Found Error' while using Wooey bootstrapper

### ISSUE THREAD

**Issue by JohnTroony** [wooey/Wooey#136]
I don't know if it's a problem on my set up, but I keep getting `FileNotFoundError` while creating a new project using Wooey bootstrapper; `wooify -p Huey`

File `requirements.txt` is not found in the project directory. Below is the actual error message from the command line:

```bash
troon@localhost:~ » wooify -p Huey                                                                                                   1 ↵
  File "/home/troon/.pyenv/shims/django-admin.py", line 3
    [ -n "$PYENV_DEBUG" ] && set -x
                      ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/usr/bin/wooify", line 9, in <module>
    load_entry_point('wooey==0.9.2', 'console_scripts', 'wooify')()
  File "/usr/lib/python3.5/site-packages/wooey/backend/command_line.py", line 91, in bootstrap
    with open(to_name, 'wb') as new_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/troon/Huey/Huey/./requirements.txt'
troon@localhost:~ » ls 
```

**Comment by Chris7** [comment]
Hey John,

Could you give me a run down on how your environment is setup so I can
reproduce this error and investigate?

**Comment by JohnTroony** [comment]
I think I've figured it out... I'm working on Arch Linux. Default Python interpreter is version 3. On BASH, python command is aliased as `/usr/bin/python2.7`. 

Creating a new virtualenv (using /usr/bin/python2.7) solves the problem. Thank you for the concern.
Fix:
```bash
$ sudo pip install virtualenv
$ virtualenv -p /usr/bin/python2.7 ProjectName
$ cd ProjectName
$ source bin/activate
$ which python
$ pip install wooey
$ wooify -p ProjectName
```

Here is the new output! :+1: 
```bash
troon@localhost:» wooify -p ProjectName
No changes detected
Operations to perform:
  Apply all migrations: sessions, admin, djcelery, kombu_transport_django, contenttypes, auth, wooey
Running migrations:
  Rendering model states... DONE
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying djcelery.0001_initial... OK
  Applying kombu_transport_django.0001_initial... OK
  Applying sessions.0001_initial... OK
  Applying wooey.0001_initial... OK
  Applying wooey.0002_remove_scriptparameter_output_path... OK
  Applying wooey.0003_populate_from_slug... OK
  Applying wooey.0004_choice_limits... OK
  Applying wooey.0005_size_bytes... OK
  Applying wooey.0006_script_group_defaults... OK
  Applying wooey.0007_script_documentation... OK
  Applying wooey.0008_short_param_admin... OK
  Applying wooey.0009_script_versioning... OK
  Applying wooey.0010_script_versioning_data_migration... OK
  Applying wooey.0011_script_versioning_cleanup... OK
  Applying wooey.0012_wooeyjob_uuid... OK
  Applying wooey.0013_wooeyjob_uuid_populate... OK
  Applying wooey.0014_wooeyjob_uuid_finalise... OK
  Applying wooey.0015_hidden_parameters... OK
....................redacted
59 static files copied to '/home/troon/ProjectName/ProjectName/static'.
Please enter the project directory ProjectName, and run python manage.py createsuperuser and python manage.py runserver to start. The admin can be found at localhost:8000/admin. You may also want to set your DJANGO_SETTINGS_MODULE environment variable to ProjectName.settings
```

**Comment by Chris7** [comment]
Thanks for the report! Glad it was a relatively straight forward fix.

**Comment by JohnTroony** [comment]
No problem, should this go on the Documentation (under install section) ?

**Comment by Chris7** [comment]
I don't think so. This is the first report, but if it comes up again -- certainly!
