### ISSUE TITLE
Cannot start Celery process

### ISSUE THREAD

**Issue by arolling** [wooey/Wooey#138]
Hi, as someone new to Django I've been trying to use Wooey as a front end to several testing scripts. Unfortunately, running them without Celery seems to block everything and crash and I can't manage to get Celery running. As per the documentation (I'm on Windows), I've been running 
```
python manage.py celery beat
python manage.py celery worker -c 1 -l info
python manage.py runserver
```
but the celery worker process never really starts. The relevant error seems to be:
```
[2016-06-22 13:53:35,522: INFO/Worker-1] child process 7068 calling self.run()
[2016-06-22 13:53:35,663: ERROR/Worker-1] Process Worker-1
Traceback (most recent call last):
  File "C:\{path}\Programs\Python\Python35-32\lib\site-packages\kombu\utils\__init__.py", line 323, in __get__
    return obj.__dict__[self.__name__]
KeyError: 'backend'
```
Then a series of cascading errors, then something like `Process 'Worker-14' pid:4992 exited with 'exitcode 1'`. I have spent a lot of time trying to google the source of the problem, but I am too new to Django and Celery to figure this out. Is there something I should have done, that is so basic it isn't in the docs?

Alternately, the scripts we are trying to run with Wooey seem to work perfectly fine with Celery flagged as false, as long as we take the threading out of them (which is used to send and receive data through a serial port). Will getting Celery running solve this problem or is this too far away from the intended usage of Wooey?

**Comment by Chris7** [comment]
Hi @arolling,

Running things with celery is recommended because otherwise you will block your website from running while a task is being executed (which happens when you set celery to False). 

Getting celery running should be your first priority. I see you are running python 3.5 32 bit -- is that supported by celery? There is also a {path} in your traceback, is that just something you removed? If possible, could you provide your project settings so I can get a better look at this?

**Comment by arolling** [comment]
Thanks so much for the help!

Yes, I did replace the innards of my computer filesystem with {path} because I didn't think it was relevant, sorry for the confusion. As far as I can tell, python 3.5 is supported by celery - the changelog mentions making a change to fix a problem with compatibility a few months ago. Like I said, I'm very new to Django so this is a pretty fresh install of everything. Which settings would you like? The user_settings.py file or something else?

**Comment by Chris7** [comment]
Sorry for the delay, was away for a trip. If you didn't change anything in the settings, then it shouldn't matter.  Can you post the full traceback?

**Comment by Chris7** [comment]
Also, could you post your machine specs? I don't run on windows, but I can check out a VM with similar settings to see if it's reproducible on my end.

**Comment by arolling** [comment]
I don't believe I changed anything in the specs, just swapped the boolean for WOOEY_CELERY back and forth (currently True), Here is a full cycle of the traceback, with some of the initial setup messages:
```
[tasks]
  . TrialScript.wooey_celery_app.debug_task
  . wooey.tasks.WooeyTask
  . wooey.tasks.submit_script

[2016-06-27 07:26:00,381: INFO/MainProcess] Connected to django://localhost//
[2016-06-27 07:26:00,418: WARNING/MainProcess] celery@Tech-PC ready.
[2016-06-27 07:26:00,751: INFO/Worker-1] child process 8396 calling self.run()
[2016-06-27 07:26:00,902: ERROR/Worker-1] Process Worker-1
Traceback (most recent call last):
  File "C:\Users\rollinga\AppData\Local\Programs\Python\Python35-32\lib\site-packages\kombu\utils\__init__.py", line 323, in __get__
    return obj.__dict__[self.__name__]
KeyError: 'backend'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\rollinga\AppData\Local\Programs\Python\Python35-32\lib\site-packages\billiard\process.py", line 292, in _bootstrap
    self.run()
  File "C:\Users\rollinga\AppData\Local\Programs\Python\Python35-32\lib\site-packages\billiard\pool.py", line 292, in run
    self.after_fork()
  File "C:\Users\rollinga\AppData\Local\Programs\Python\Python35-32\lib\site-packages\billiard\pool.py", line 395, in after_fork
    self.initializer(*self.initargs)
  File "C:\Users\rollinga\AppData\Local\Programs\Python\Python35-32\lib\site-packages\celery\concurrency\prefork.py", line 81, in process_initializer
    app=app)
  File "C:\Users\rollinga\AppData\Local\Programs\Python\Python35-32\lib\site-packages\celery\app\trace.py", line 161, in build_tracer
    backend = task.backend
  File "C:\Users\rollinga\AppData\Local\Programs\Python\Python35-32\lib\site-packages\celery\app\task.py", line 930, in backend
    return self.app.backend
  File "C:\Users\rollinga\AppData\Local\Programs\Python\Python35-32\lib\site-packages\kombu\utils\__init__.py", line 325, in __get__
    value = obj.__dict__[self.__name__] = self.__get(obj)
  File "C:\Users\rollinga\AppData\Local\Programs\Python\Python35-32\lib\site-packages\celery\app\base.py", line 626, in backend
    return self._get_backend()
  File "C:\Users\rollinga\AppData\Local\Programs\Python\Python35-32\lib\site-packages\celery\app\base.py", line 444, in _get_backend
    self.loader)
  File "C:\Users\rollinga\AppData\Local\Programs\Python\Python35-32\lib\site-packages\celery\backends\__init__.py", line 68, in get_backend_by_url
    return get_backend_cls(backend, loader), url
  File "C:\Users\rollinga\AppData\Local\Programs\Python\Python35-32\lib\site-packages\celery\backends\__init__.py", line 49, in get_backend_cls
    cls = symbol_by_name(backend, aliases)
  File "C:\Users\rollinga\AppData\Local\Programs\Python\Python35-32\lib\site-packages\kombu\utils\__init__.py", line 96, in symbol_by_name
    module = imp(module_name, package=package, **kwargs)
  File "C:\Users\rollinga\AppData\Local\Programs\Python\Python35-32\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 662, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "C:\Users\rollinga\AppData\Local\Programs\Python\Python35-32\lib\site-packages\djcelery\backends\database.py", line 7, in <module>
    from ..models import TaskMeta, TaskSetMeta
  File "C:\Users\rollinga\AppData\Local\Programs\Python\Python35-32\lib\site-packages\djcelery\models.py", line 30, in <module>
    class TaskMeta(models.Model):
  File "C:\Users\rollinga\AppData\Local\Programs\Python\Python35-32\lib\site-packages\django\db\models\base.py", line 94, in __new__
    app_config = apps.get_containing_app_config(module)
  File "C:\Users\rollinga\AppData\Local\Programs\Python\Python35-32\lib\site-packages\django\apps\registry.py", line 239, in get_containing_app_config
    self.check_apps_ready()
  File "C:\Users\rollinga\AppData\Local\Programs\Python\Python35-32\lib\site-packages\django\apps\registry.py", line 124, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.
[2016-06-27 07:26:00,902: ERROR/Worker-1] Process Worker-1
Traceback (most recent call last):
  File "C:\Users\rollinga\AppData\Local\Programs\Python\Python35-32\lib\site-packages\kombu\utils\__init__.py", line 323, in __get__
    return obj.__dict__[self.__name__]
KeyError: 'backend'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\rollinga\AppData\Local\Programs\Python\Python35-32\lib\site-packages\billiard\process.py", line 292, in _bootstrap
    self.run()
  File "C:\Users\rollinga\AppData\Local\Programs\Python\Python35-32\lib\site-packages\billiard\pool.py", line 292, in run
    self.after_fork()
  File "C:\Users\rollinga\AppData\Local\Programs\Python\Python35-32\lib\site-packages\billiard\pool.py", line 395, in after_fork
    self.initializer(*self.initargs)
  File "C:\Users\rollinga\AppData\Local\Programs\Python\Python35-32\lib\site-packages\celery\concurrency\prefork.py", line 81, in process_initializer
    app=app)
  File "C:\Users\rollinga\AppData\Local\Programs\Python\Python35-32\lib\site-packages\celery\app\trace.py", line 161, in build_tracer
    backend = task.backend
  File "C:\Users\rollinga\AppData\Local\Programs\Python\Python35-32\lib\site-packages\celery\app\task.py", line 930, in backend
    return self.app.backend
  File "C:\Users\rollinga\AppData\Local\Programs\Python\Python35-32\lib\site-packages\kombu\utils\__init__.py", line 325, in __get__
    value = obj.__dict__[self.__name__] = self.__get(obj)
  File "C:\Users\rollinga\AppData\Local\Programs\Python\Python35-32\lib\site-packages\celery\app\base.py", line 626, in backend
    return self._get_backend()
  File "C:\Users\rollinga\AppData\Local\Programs\Python\Python35-32\lib\site-packages\celery\app\base.py", line 444, in _get_backend
    self.loader)
  File "C:\Users\rollinga\AppData\Local\Programs\Python\Python35-32\lib\site-packages\celery\backends\__init__.py", line 68, in get_backend_by_url
    return get_backend_cls(backend, loader), url
  File "C:\Users\rollinga\AppData\Local\Programs\Python\Python35-32\lib\site-packages\celery\backends\__init__.py", line 49, in get_backend_cls
    cls = symbol_by_name(backend, aliases)
  File "C:\Users\rollinga\AppData\Local\Programs\Python\Python35-32\lib\site-packages\kombu\utils\__init__.py", line 96, in symbol_by_name
    module = imp(module_name, package=package, **kwargs)
  File "C:\Users\rollinga\AppData\Local\Programs\Python\Python35-32\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 662, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "C:\Users\rollinga\AppData\Local\Programs\Python\Python35-32\lib\site-packages\djcelery\backends\database.py", line 7, in <module>
    from ..models import TaskMeta, TaskSetMeta
  File "C:\Users\rollinga\AppData\Local\Programs\Python\Python35-32\lib\site-packages\djcelery\models.py", line 30, in <module>
    class TaskMeta(models.Model):
  File "C:\Users\rollinga\AppData\Local\Programs\Python\Python35-32\lib\site-packages\django\db\models\base.py", line 94, in __new__
    app_config = apps.get_containing_app_config(module)
  File "C:\Users\rollinga\AppData\Local\Programs\Python\Python35-32\lib\site-packages\django\apps\registry.py", line 239, in get_containing_app_config
    self.check_apps_ready()
  File "C:\Users\rollinga\AppData\Local\Programs\Python\Python35-32\lib\site-packages\django\apps\registry.py", line 124, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.
[2016-06-27 07:26:01,266: ERROR/MainProcess] Process 'Worker-1' pid:8396 exited with 'exitcode 1'
[2016-06-27 07:26:01,622: INFO/Worker-1] child process 6192 calling self.run()
[2016-06-27 07:26:01,807: ERROR/Worker-1] Process Worker-1
Traceback (most recent call last):
  File "C:\Users\rollinga\AppData\Local\Programs\Python\Python35-32\lib\site-packages\kombu\utils\__init__.py", line 323, in __get__
    return obj.__dict__[self.__name__]
KeyError: 'backend'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\rollinga\AppData\Local\Programs\Python\Python35-32\lib\site-packages\billiard\process.py", line 292, in _bootstrap
    self.run()
  File "C:\Users\rollinga\AppData\Local\Programs\Python\Python35-32\lib\site-packages\billiard\pool.py", line 292, in run
    self.after_fork()
  File "C:\Users\rollinga\AppData\Local\Programs\Python\Python35-32\lib\site-packages\billiard\pool.py", line 395, in after_fork
    self.initializer(*self.initargs)
  File "C:\Users\rollinga\AppData\Local\Programs\Python\Python35-32\lib\site-packages\celery\concurrency\prefork.py", line 81, in process_initializer
    app=app)
  File "C:\Users\rollinga\AppData\Local\Programs\Python\Python35-32\lib\site-packages\celery\app\trace.py", line 161, in build_tracer
    backend = task.backend
  File "C:\Users\rollinga\AppData\Local\Programs\Python\Python35-32\lib\site-packages\celery\app\task.py", line 930, in backend
    return self.app.backend
  File "C:\Users\rollinga\AppData\Local\Programs\Python\Python35-32\lib\site-packages\kombu\utils\__init__.py", line 325, in __get__
    value = obj.__dict__[self.__name__] = self.__get(obj)
  File "C:\Users\rollinga\AppData\Local\Programs\Python\Python35-32\lib\site-packages\celery\app\base.py", line 626, in backend
    return self._get_backend()
  File "C:\Users\rollinga\AppData\Local\Programs\Python\Python35-32\lib\site-packages\celery\app\base.py", line 444, in _get_backend
    self.loader)
  File "C:\Users\rollinga\AppData\Local\Programs\Python\Python35-32\lib\site-packages\celery\backends\__init__.py", line 68, in get_backend_by_url
    return get_backend_cls(backend, loader), url
  File "C:\Users\rollinga\AppData\Local\Programs\Python\Python35-32\lib\site-packages\celery\backends\__init__.py", line 49, in get_backend_cls
    cls = symbol_by_name(backend, aliases)
  File "C:\Users\rollinga\AppData\Local\Programs\Python\Python35-32\lib\site-packages\kombu\utils\__init__.py", line 96, in symbol_by_name
    module = imp(module_name, package=package, **kwargs)
  File "C:\Users\rollinga\AppData\Local\Programs\Python\Python35-32\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 662, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "C:\Users\rollinga\AppData\Local\Programs\Python\Python35-32\lib\site-packages\djcelery\backends\database.py", line 7, in <module>
    from ..models import TaskMeta, TaskSetMeta
  File "C:\Users\rollinga\AppData\Local\Programs\Python\Python35-32\lib\site-packages\djcelery\models.py", line 30, in <module>
    class TaskMeta(models.Model):
  File "C:\Users\rollinga\AppData\Local\Programs\Python\Python35-32\lib\site-packages\django\db\models\base.py", line 94, in __new__
    app_config = apps.get_containing_app_config(module)
  File "C:\Users\rollinga\AppData\Local\Programs\Python\Python35-32\lib\site-packages\django\apps\registry.py", line 239, in get_containing_app_config
    self.check_apps_ready()
  File "C:\Users\rollinga\AppData\Local\Programs\Python\Python35-32\lib\site-packages\django\apps\registry.py", line 124, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.
[2016-06-27 07:26:01,807: ERROR/Worker-1] Process Worker-1
```
This then repeats, roughly every second, until I Ctrl-C a few times to break out of it.

My laptop is running 64-bit Windows 10 Pro on an Intel 2.6 GHz processor. Django version 1.9.7, Python 3.5 as mentioned above, and pretty much everything else relevant was installed as dependencies when I installed Wooey. Is there anything else I'm leaving out? Thanks again for helping a total newbie!

**Comment by Chris7** [comment]
I updated our CI tests to see if it's an issue with 3.5 and Django 1.9. Could you try installing django 1.8 and check if that works?

**Comment by arolling** [comment]
This worked! Or at least, the celery process worked; now I need to rewrite the script so it actually closes/ends properly. BTW, the "No Arguments" sample script still won't run, but now there are no error messages at all.

**Comment by arolling** [comment]
Actually, I spoke too soon. Now the choices script, which had been working before, is failing; it goes to the screen where the console display is, but is "waiting" eternally.

**Comment by arolling** [comment]
Here are the messages on the celery worker window:
```

 -------------- celery@Tech-PC v3.1.23 (Cipater)
---- **** -----
--- * ***  * -- Windows-10-10.0.10586-SP0
-- * - **** ---
- ** ---------- [config]
- ** ---------- .> app:         default:0x35ec6d0 (.default.Loader)
- ** ---------- .> transport:   django://localhost//
- ** ---------- .> results:
- *** --- * --- .> concurrency: 1 (prefork)
-- ******* ----
--- ***** ----- [queues]
 -------------- .> celery           exchange=celery(direct) key=celery


[tasks]
  . TrialScript.wooey_celery_app.debug_task
  . wooey.tasks.WooeyTask
  . wooey.tasks.submit_script

[2016-06-27 10:03:06,573: INFO/MainProcess] Connected to django://localhost//
[2016-06-27 10:03:06,589: WARNING/MainProcess] celery@Tech-PC ready.
[2016-06-27 10:03:06,636: INFO/MainProcess] Received task: wooey.tasks.submit_script[82b83df8-4c99-4b38-b9e4-11695b96a092]
[2016-06-27 10:03:06,870: INFO/Worker-1] child process 6472 calling self.run()
[2016-06-27 10:03:07,698: INFO/MainProcess] Task wooey.tasks.submit_script[82b83df8-4c99-4b38-b9e4-11695b96a092] succeeded in 0.28100000001722947s: (b'Namespace(all_choices=None, at_least_one_choice=None, choices_str=None, more_multiple_file_choices=None,...
[2016-06-27 10:03:26,695: INFO/MainProcess] Received task: wooey.tasks.submit_script[ecd34017-902c-4360-a492-a8cb8869bca0]
[2016-06-27 10:03:26,898: INFO/MainProcess] Task wooey.tasks.submit_script[ecd34017-902c-4360-a492-a8cb8869bca0] succeeded in 0.2029999999795109s: (b'Namespace(all_choices=None, at_least_one_choice=None, choices_str=None, more_multiple_file_choices=None,...
[2016-06-27 10:03:51,733: INFO/MainProcess] Received task: wooey.tasks.submit_script[817f75a1-a596-4bb3-a15a-7eaabbdefc0c]
[2016-06-27 10:03:51,970: INFO/MainProcess] Task wooey.tasks.submit_script[817f75a1-a596-4bb3-a15a-7eaabbdefc0c] succeeded in 0.23399999999674037s: (b'Namespace(all_choices=None, at_least_one_choice=None, choices_str=None, more_multiple_file_choices=None,...
[2016-06-27 10:05:31,881: INFO/MainProcess] Received task: wooey.tasks.submit_script[43e940e7-c780-4777-8537-f5006b6df300]
[2016-06-27 10:05:32,127: INFO/MainProcess] Task wooey.tasks.submit_script[43e940e7-c780-4777-8537-f5006b6df300] succeeded in 0.23499999998603016s: (b'Namespace(all_choices=None, at_least_one_choice=None, choices_str=None, more_multiple_file_choices=None,...
[2016-06-27 12:00:03,077: INFO/MainProcess] Received task: wooey.tasks.submit_script[eb370b44-8fac-4019-9694-c1250b739b44]
[2016-06-27 12:00:04,345: INFO/MainProcess] Task wooey.tasks.submit_script[eb370b44-8fac-4019-9694-c1250b739b44] succeeded in 1.25s: (b'', b'')
[2016-06-27 14:22:51,761: INFO/MainProcess] Received task: wooey.tasks.submit_script[7f20448a-d18a-4212-85c8-47b1277b526d]
[2016-06-27 14:22:52,840: INFO/MainProcess] Task wooey.tasks.submit_script[7f20448a-d18a-4212-85c8-47b1277b526d] succeeded in 1.047000000020489s: (b'', b'')
[2016-06-27 14:23:41,867: INFO/MainProcess] Received task: wooey.tasks.submit_script[a920f955-54d4-44c6-9bd8-9200762a7e83]
[2016-06-27 14:23:42,097: INFO/MainProcess] Task wooey.tasks.submit_script[a920f955-54d4-44c6-9bd8-9200762a7e83] succeeded in 0.21799999999348074s: (b'', b'Traceback (most recent call last):\r\n  File...
[2016-06-27 14:27:22,293: INFO/MainProcess] Received task: wooey.tasks.submit_script[3bb5b096-8b91-4c04-bb28-5f2ff131d0cd]
[2016-06-27 14:27:34,601: INFO/MainProcess] Task wooey.tasks.submit_script[3bb5b096-8b91-4c04-bb28-5f2ff131d0cd] succeeded in 12.311999999976251s: (b'[1]\r\nCOM5\r\n0\r\n1\r\n2\r\n3\r\n4\r\n5\r\n6\r\n7\r\n8\r\n9\r\n10\r\n11\r\n12\r\n13\r\n14\r\n15\r\n16\r\n17\r\n18\r\n19\r\n...
```

The scripts seem to be running, and the results are saved - you can navigate to the results page for a job - but the initial page you are brought to after clicking "Submit" never updates and continues to say "Waiting". Any suggestions for what I might have wrong now? Thanks again!

**Comment by Chris7** [comment]
Ah, that is because the latest public release doesn't have live reloads enabled. I'll publish a dev edition this week so you may upgrade.

**Comment by arolling** [comment]
Thanks so much - I had decided that it was a Windows compatibility issue with Celery and installed an Ubuntu VM to check, but of course that exhibits the same problem.

**Comment by Chris7** [comment]
Good to hear everything worked out! Look back in a week or so and we should have the latest version out.
