### ISSUE TITLE
Django 1.10 incompatibility / version pinning 

### ISSUE THREAD

**Issue by gourneau** [wooey/Wooey#150]
Hey,

Wooey is a great tool thanks for sharing!

Just a heads up it is not working with Django 1.10 which came out yesterday, and what the requirements.txt will install right now. Perhaps just pin Django to 1.9.9 for now. 

Here is an exception that is hit when trying to start a new project. The problem is Django 1.10, everything works fine with Django 1.9.9

```
josh@desktop:~$ wooify -p ProjectName
Traceback (most recent call last):
  File "/home/josh/miniconda2/bin/wooify", line 7, in <module>
    from wooey.backend.command_line import bootstrap
  File "/home/josh/miniconda2/lib/python2.7/site-packages/wooey/backend/command_line.py", line 18, in <module>
    from .. import django_compat
  File "/home/josh/miniconda2/lib/python2.7/site-packages/wooey/django_compat.py", line 40, in <module>
    get_template_from_string = Engine.get_default().from_string
  File "/home/josh/miniconda2/lib/python2.7/site-packages/django/utils/lru_cache.py", line 124, in wrapper
    result = user_function(*args, **kwds)
  File "/home/josh/miniconda2/lib/python2.7/site-packages/django/template/engine.py", line 81, in get_default
    "No DjangoTemplates backend is configured.")
django.core.exceptions.ImproperlyConfigured: No DjangoTemplates backend is configured.
```

**Comment by Chris7** [comment]
Thanks @gourneau. I'll push a new release soon that pins up to 1.9 until we have explicit support for 1.10

**Comment by childrss** [comment]
Not to be rude, but got bit by this issue too... It wasn't a complete waste of time going through the Wooey docs and googling as I learned something, but...

**Comment by Chris7** [comment]
I'll just update the version to pin it to <1.10. It should have been done, but I was overly optimistic on how long it would take to get a complete solution to #148

**Comment by childrss** [comment]
Thanks much!

**Comment by Chris7** [comment]
Pushed 0.9.4 with version pinning in setup.py
