### ISSUE TITLE
Start a new project error

### ISSUE THREAD

**Issue by zjhzxjm** [wooey/Wooey#161]
Hey,

I can not start a new project, need your help.

**All dependencies have been installed by pip:**
amqp (2.1.1)
billiard (3.5.0.2)
celery (4.0.0)
clinto (0.1.3)
Django (1.9.11)
django-autoslug (1.9.3)
django-celery (3.1.17)
kombu (4.0.0)
pip (9.0.1)
pytz (2016.7)
setuptools (27.2.0)
six (1.10.0)
vine (1.1.3)
wheel (0.29.0)
wooey (0.9.5)

**Here is an exception that is hit when trying to start a new project.** 

$wooify -p realcloud
Traceback (most recent call last):
  File "/home/xujm/soft/Anaconda/anaconda3/envs/wooey/lib/python3.5/site-packages/django/apps/config.py", line 118, in create
    cls = getattr(mod, cls_name)
AttributeError: module 'kombu.transport' has no attribute 'django'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "realcloud/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/xujm/soft/Anaconda/anaconda3/envs/wooey/lib/python3.5/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/home/xujm/soft/Anaconda/anaconda3/envs/wooey/lib/python3.5/site-packages/django/core/management/__init__.py", line 327, in execute
    django.setup()
  File "/home/xujm/soft/Anaconda/anaconda3/envs/wooey/lib/python3.5/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/xujm/soft/Anaconda/anaconda3/envs/wooey/lib/python3.5/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/home/xujm/soft/Anaconda/anaconda3/envs/wooey/lib/python3.5/site-packages/django/apps/config.py", line 123, in create
    import_module(entry)
  File "/home/xujm/soft/Anaconda/anaconda3/envs/wooey/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named 'kombu.transport.django'
Traceback (most recent call last):
  File "/home/xujm/soft/Anaconda/anaconda3/envs/wooey/lib/python3.5/site-packages/django/apps/config.py", line 118, in create
    cls = getattr(mod, cls_name)
AttributeError: module 'kombu.transport' has no attribute 'django'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "realcloud/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/xujm/soft/Anaconda/anaconda3/envs/wooey/lib/python3.5/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/home/xujm/soft/Anaconda/anaconda3/envs/wooey/lib/python3.5/site-packages/django/core/management/__init__.py", line 327, in execute
    django.setup()
  File "/home/xujm/soft/Anaconda/anaconda3/envs/wooey/lib/python3.5/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/xujm/soft/Anaconda/anaconda3/envs/wooey/lib/python3.5/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/home/xujm/soft/Anaconda/anaconda3/envs/wooey/lib/python3.5/site-packages/django/apps/config.py", line 123, in create
    import_module(entry)
  File "/home/xujm/soft/Anaconda/anaconda3/envs/wooey/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named 'kombu.transport.django'
Traceback (most recent call last):
  File "/home/xujm/soft/Anaconda/anaconda3/envs/wooey/lib/python3.5/site-packages/django/apps/config.py", line 118, in create
    cls = getattr(mod, cls_name)
AttributeError: module 'kombu.transport' has no attribute 'django'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "realcloud/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/xujm/soft/Anaconda/anaconda3/envs/wooey/lib/python3.5/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/home/xujm/soft/Anaconda/anaconda3/envs/wooey/lib/python3.5/site-packages/django/core/management/__init__.py", line 327, in execute
    django.setup()
  File "/home/xujm/soft/Anaconda/anaconda3/envs/wooey/lib/python3.5/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/xujm/soft/Anaconda/anaconda3/envs/wooey/lib/python3.5/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/home/xujm/soft/Anaconda/anaconda3/envs/wooey/lib/python3.5/site-packages/django/apps/config.py", line 123, in create
    import_module(entry)
  File "/home/xujm/soft/Anaconda/anaconda3/envs/wooey/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named 'kombu.transport.django'
Please enter the project directory realcloud, and run python manage.py createsuperuser and python manage.py runserver to start. The admin can be found at localhost:8000/admin. You may also want to set your DJANGO_SETTINGS_MODULE environment variable to realcloud.settings

**Comment by Chris7** [comment]
It's because django-celery hasn't yet be updated to lock in the correct
version of celery. I'm away until Monday but if it's not fixed by then,
I'll update pypi with the celery versions locked in. For now, you can fix
it by `pip install celery<4.0.0`. You may need to uninstall kombu and
celery first to get all the correct dependencies.

**Comment by zjhzxjm** [comment]
Ok, Thanks. I will try it by your suggestion

**Comment by Chris7** [comment]
Updated latest on pypi to fix this. Sorry for the delay!

**Comment by haricot** [comment]
There is a migration problem with the version of  django-celery (3.1.17), version  django-celery (3.2.0) resolves this.

---

$ pip search wooey 
Wooey (0.9.6)  - A Django app which creates a web GUI and task interface for argparse scripts

$ wooify -p wooey_project

$ cd wooey_project

$ ./manage.py migrate 
Operations to perform:
  Apply all migrations: djcelery, kombu_transport_django, admin, auth, sessions, contenttypes, wooey
Running migrations:
  No migrations to apply.
  Your models have changes that are not yet reflected in a migration, and so won't be applied.
  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.


$ ./manage.py makemigrations
Migrations for 'djcelery':
  0005_auto_20161202_0826.py:
    - Alter field status on taskmeta

$ ./manage.py migrate 
Operations to perform:
  Apply all migrations: djcelery, wooey, sessions, contenttypes, kombu_transport_django, auth, admin
Running migrations:
  Rendering model states... DONE
  Applying djcelery.0005_auto_20161202_0826... OK

$ ./manage.py migrate 
Operations to perform:
  Apply all migrations: djcelery, contenttypes, kombu_transport_django, wooey, sessions, auth, admin
Running migrations:
  No migrations to apply.
  Your models have changes that are not yet reflected in a migration, and so won't be applied.
  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.

---

if we change django-celery (3.1.17)  to  django-celery (3.2.0) in wooey_project/wooey_project/requirements.txt

Django
wooey
django-sslify
django-storages
git+https://github.com/celery/django-celery@v3.2.0
django-autoslug
boto
waitress
psycopg2
collectfast
honcho


$ pip install -r wooey_project/requirements.txt

$ ./manage.py migrate 
Operations to perform:
  Apply all migrations: auth, djcelery, sessions, admin, contenttypes, wooey, kombu_transport_django
Running migrations:
  No migrations to apply.
  Your models have changes that are not yet reflected in a migration, and so won't be applied.
  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.

$ ./manage.py makemigrations
Migrations for 'djcelery':
  0006_auto_20161202_0839.py:
    - Alter field status on taskmeta
    - Alter field state on taskstate

$ ./manage.py migrate 
Operations to perform:
  Apply all migrations: wooey, auth, sessions, contenttypes, kombu_transport_django, djcelery, admin
Running migrations:
  Rendering model states... DONE
  Applying djcelery.0006_auto_20161202_0839... OK

$ ./manage.py migrate 
Operations to perform:
  Apply all migrations: djcelery, kombu_transport_django, contenttypes, sessions, admin, wooey, auth
Running migrations:
  No migrations to apply.

**Comment by Chris7** [comment]
Do you mind posting what is in the migration? I've been waiting on django-celery to release to pypi but it's been over a week since their 3.2 tag.

**Comment by haricot** [comment]
Thank you for replying.
I hope this is what you want :

With django-celery (3.2.0) :

$ ./manage.py sqlmigrate   djcelery     0006_auto_20161202_0839
BEGIN;
--
-- Alter field status on taskmeta
--
ALTER TABLE "celery_taskmeta" RENAME TO "celery_taskmeta__old";
CREATE TABLE "celery_taskmeta" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "status" varchar(50) NOT NULL, "task_id" varchar(255) NOT NULL UNIQUE, "result" text NULL, "date_done" datetime NOT NULL, "traceback" text NULL, "hidden" bool NOT NULL, "meta" text NULL);
INSERT INTO "celery_taskmeta" ("traceback", "status", "meta", "date_done", "result", "id", "task_id", "hidden") SELECT "traceback", "status", "meta", "date_done", "result", "id", "task_id", "hidden" FROM "celery_taskmeta__old";
DROP TABLE "celery_taskmeta__old";
CREATE INDEX "celery_taskmeta_662f707d" ON "celery_taskmeta" ("hidden");
--
-- Alter field state on taskstate
--
ALTER TABLE "djcelery_taskstate" RENAME TO "djcelery_taskstate__old";
CREATE TABLE "djcelery_taskstate" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "task_id" varchar(36) NOT NULL UNIQUE, "name" varchar(200) NULL, "tstamp" datetime NOT NULL, "args" text NULL, "kwargs" text NULL, "eta" datetime NULL, "expires" datetime NULL, "result" text NULL, "traceback" text NULL, "runtime" real NULL, "retries" integer NOT NULL, "hidden" bool NOT NULL, "worker_id" integer NULL REFERENCES "djcelery_workerstate" ("id"), "state" varchar(64) NOT NULL);
INSERT INTO "djcelery_taskstate" ("runtime", "retries", "worker_id", "result", "task_id", "hidden", "expires", "kwargs", "traceback", "name", "args", "state", "id", "eta", "tstamp") SELECT "runtime", "retries", "worker_id", "result", "task_id", "hidden", "expires", "kwargs", "traceback", "name", "args", "state", "id", "eta", "tstamp" FROM "djcelery_taskstate__old";
DROP TABLE "djcelery_taskstate__old";
CREATE INDEX "djcelery_taskstate_b068931c" ON "djcelery_taskstate" ("name");
CREATE INDEX "djcelery_taskstate_863bb2ee" ON "djcelery_taskstate" ("tstamp");
CREATE INDEX "djcelery_taskstate_662f707d" ON "djcelery_taskstate" ("hidden");
CREATE INDEX "djcelery_taskstate_ce77e6ef" ON "djcelery_taskstate" ("worker_id");
CREATE INDEX "djcelery_taskstate_9ed39e2e" ON "djcelery_taskstate" ("state");

COMMIT;

**Comment by haricot** [comment]
I think that's what you're asking me, sorry

$cat venv/lib/python3.5/site-packages/djcelery/migrations/0006_auto_20161202_0839.py :

```
# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-12-02 08:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djcelery', '0005_auto_20161202_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmeta',
            name='status',
            field=models.CharField(choices=[('FAILURE', 'FAILURE'), ('PENDING', 'PENDING'), ('RECEIVED', 'RECEIVED'), ('RETRY', 'RETRY'), ('REVOKED', 'REVOKED'), ('STARTED', 'STARTED'), ('SUCCESS', 'SUCCESS')], default='PENDING', max_length=50, verbose_name='state'),
        ),
        migrations.AlterField(
            model_name='taskstate',
            name='state',
            field=models.CharField(choices=[('FAILURE', 'FAILURE'), ('PENDING', 'PENDING'), ('RECEIVED', 'RECEIVED'), ('RETRY', 'RETRY'), ('REVOKED', 'REVOKED'), ('STARTED', 'STARTED'), ('SUCCESS', 'SUCCESS')], db_index=True, max_length=64, verbose_name='state'),
        ),
    ]
```

**Comment by haricot** [comment]
This corresponds to this issue of django-celery  3.1.17
https://github.com/celery/django-celery/issues/422
