### ISSUE TITLE
file write in script

### ISSUE THREAD

**Issue by etiaxie** [wooey/Wooey#177]
i use the simple python script as following:
import argparse
import sys
from auto_hik import *

parser = argparse.ArgumentParser(description="Find the sum of all the numbers below a certain number.")
parser.add_argument('--below', help='The number to find the sum of numbers below.', type=int, default=99)

def main():
    args = parser.parse_args()
    ssh_command('10.192.74.100', 'pwd')
    with open(os.path.join(os.getcwd(),'a.txt'), 'w') as f:
        f.write('bbb')

if __name__ == '__main__':
    main()

when run it,I get unicode error in wondows console like this:
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 149, i
n get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 147, i
n get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\django\views\generic\base.py", line 68, in
 view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Python27\lib\site-packages\django\views\generic\base.py", line 88, in
 dispatch
    return handler(request, *args, **kwargs)
  File "C:\Python27\lib\site-packages\wooey\views\views.py", line 160, in post
    data = super(WooeyScriptView, self).post(*args, **kwargs)
  File "C:\Python27\lib\site-packages\wooey\views\views.py", line 131, in post
    job.submit_to_celery()
  File "C:\Python27\lib\site-packages\wooey\models\core.py", line 208, in submit
_to_celery
    results = tasks.submit_script(**task_kwargs)
  File "C:\Python27\lib\site-packages\celery\app\task.py", line 428, in __call__

    return self.run(*args, **kwargs)
  File "C:\Python27\lib\site-packages\wooey\tasks.py", line 195, in submit_scrip
t
    utils.create_job_fileinfo(job)
  File "C:\Python27\lib\site-packages\wooey\backend\utils.py", line 531, in crea
te_job_fileinfo
    checksum = get_checksum(filepath, extra=[job.pk, full_path, 'output'])
  File "C:\Python27\lib\site-packages\wooey\backend\utils.py", line 616, in get_
checksum
    hasher.update(six.u(str(i)).encode('utf-8'))
  File "C:\Python27\lib\site-packages\six.py", line 647, in u
    return unicode(s.replace(r'\\', r'\\\\'), "unicode_escape")
UnicodeDecodeError: 'unicodeescape' codec can't decode bytes in position 11-12:
truncated \xXX escape

**Comment by Chris7** [comment]
Thanks for including an example! I don't have a windows box accessible ATM but will work on setting up a VM to reproduce this.

**Comment by Chris7** [comment]
Hi @etiaxie,

Can you give me more information on your setup? I just tried replicating this with your script in Windows 7 with the latest version of Wooey from pypi, but the script ran fine.

**Comment by Chris7** [comment]
Closing due to no response. Let me know if this is still an issue @etiaxie
