### ISSUE TITLE
Adding a script - ArgParse error.

### ISSUE THREAD

**Issue by somabc** [wooey/Wooey#191]
I'm having problems adding a script to Wooey.

comparator.py from [https://github.com/johnwickerson/memalloy/tree/master/top](url)

`Converting comparator.py
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/python2.7/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/lib/python2.7/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/usr/lib/python2.7/site-packages/wooey/management/commands/addscript.py", line 73, in handle
    res = add_wooey_script(**add_kwargs)
  File "/usr/lib/python2.7/site-packages/wooey/backend/utils.py", line 245, in add_wooey_script
    parser = Parser(script_name=filename, script_path=local_storage.path(local_file))
  File "/usr/lib/python2.7/site-packages/clinto/parser.py", line 19, in __init__
    parser_obj = [pc(script_path, script_source) for pc in parsers]
  File "/usr/lib/python2.7/site-packages/clinto/parsers/base.py", line 43, in __init__
    self.process_parser()
  File "/usr/lib/python2.7/site-packages/clinto/parsers/argparse_.py", line 262, in process_parser
    node = ArgParseNode(action=action)
  File "/usr/lib/python2.7/site-packages/clinto/parsers/argparse_.py", line 140, in __init__
    self.node_attrs = dict([(i, field_type[i]) for i in GLOBAL_ATTRS])
TypeError: 'NoneType' object has no attribute '__getitem__'
`

Any pointers on how to rewrite this to be wooey compatible?

**Comment by Chris7** [comment]
Hi @somabc,

It's failing because the script is performing relative imports using absolute import syntax. This bit at the top:
```
import argparsing
from argparsing import TOOL_PATH
import setup_result_dir
import run_alloy
import remove_dups
```
is all from the current directory. Wooey uploads a script to the server, so thus it does not have access to relative imports in the script, only absolute imports. Wooey works with stand alone scripts, so it should be made to be stand-alone.

The next problem is the argparser is created inside a function. Wooey works by introspection, and thus cannot access that object since it doesn't exist until the function is called and wooey has no knowledge of what function should be called (it's a catch-22). So the next bit is the argparser instance needs to be instantiated globally, or in the `if __name__ == '__main__'` bit. 

Hope that helps!
