### ISSUE TITLE
 AttributeError: 'str' object has no attribute 'get'

### ISSUE THREAD

**Issue by pymenow** [wooey/Wooey#199]
I get this error with any script I import. 

I am using this with anaconda 3 -
param_group_name = param_group_info.get('group')
AttributeError: 'str' object has no attribute 'get'

Converting ../test.py
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/anaconda/anaconda3/lib/python3.6/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/opt/anaconda/anaconda3/lib/python3.6/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/anaconda/anaconda3/lib/python3.6/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/anaconda/anaconda3/lib/python3.6/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/opt/anaconda/anaconda3/lib/python3.6/site-packages/wooey/management/commands/addscript.py", line 73, in handle
    res = add_wooey_script(**add_kwargs)
  File "/opt/anaconda/anaconda3/lib/python3.6/site-packages/wooey/backend/utils.py", line 309, in add_wooey_script
    param_group_name = param_group_info.get('group')
AttributeError: 'str' object has no attribute 'get'

I am using the code from https://github.com/wooey/Wooey/blob/master/wooey/tests/scripts/heatmap.py

**Comment by Chris7** [comment]
This is my fault. I didn't lock the version of `clinto` (clinto parses scripts for Wooey) to a maximum version for the latest release, and there is an updated version that is incompatible with the latest Wooey. To fix this, you can install the previous minor version of `clinto` with `pip install "clinto<0.2.0"`. It should be remedied shortly, as I'm finishing up some documentation changes in Wooey for the next update.

**Comment by Chris7** [comment]
I issues a patch release of Wooey that addresses this. You can upgrade wooey to version 0.9.10 (which will downgrade clinto for you). Thank you for the report @pymenow.

**Comment by pymenow** [comment]
@Chris7 thank you for a quick response on that.
pip install --upgrade wooey
Successfully installed clinto-0.1.4 pytz-2017.3 wooey-0.9.10

Will post back once I test.

**Comment by pymenow** [comment]
Seem to have other issues now after the upgrade. 
traceback with Wooify on windows : 

Traceback (most recent call last):
  File "AMS\manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "c:\programdata\anaconda3\lib\site-packages\django\core\management\__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "c:\programdata\anaconda3\lib\site-packages\django\core\management\__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "c:\programdata\anaconda3\lib\site-packages\django\core\management\base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "c:\programdata\anaconda3\lib\site-packages\django\core\management\base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "c:\programdata\anaconda3\lib\site-packages\django\core\management\commands\makemigrations.py", line 65, in handle
    loader = MigrationLoader(None, ignore_no_migrations=True)
  File "c:\programdata\anaconda3\lib\site-packages\django\db\migrations\loader.py", line 49, in __init__
    self.build_graph()
  File "c:\programdata\anaconda3\lib\site-packages\django\db\migrations\loader.py", line 293, in build_graph
    _reraise_missing_dependency(migration, parent, e)
  File "c:\programdata\anaconda3\lib\site-packages\django\db\migrations\loader.py", line 276, in _reraise_missing_dependency
    raise exc
  File "c:\programdata\anaconda3\lib\site-packages\django\db\migrations\loader.py", line 286, in build_graph
    self.graph.add_dependency(migration, key, parent)
  File "c:\programdata\anaconda3\lib\site-packages\django\db\migrations\graph.py", line 126, in add_dependency
    parent
django.db.migrations.exceptions.NodeNotFoundError: Migration wooey.0029_auto_20171211_0145 dependencies reference nonexistent parent node ('wooey', '0028_add_script_subparser')
Traceback (most recent call last):
  File "AMS\manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "c:\programdata\anaconda3\lib\site-packages\django\core\management\__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "c:\programdata\anaconda3\lib\site-packages\django\core\management\__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "c:\programdata\anaconda3\lib\site-packages\django\core\management\base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "c:\programdata\anaconda3\lib\site-packages\django\core\management\base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "c:\programdata\anaconda3\lib\site-packages\django\core\management\commands\migrate.py", line 89, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "c:\programdata\anaconda3\lib\site-packages\django\db\migrations\executor.py", line 20, in __init__
    self.loader = MigrationLoader(self.connection)
  File "c:\programdata\anaconda3\lib\site-packages\django\db\migrations\loader.py", line 49, in __init__
    self.build_graph()
  File "c:\programdata\anaconda3\lib\site-packages\django\db\migrations\loader.py", line 293, in build_graph
    _reraise_missing_dependency(migration, parent, e)
  File "c:\programdata\anaconda3\lib\site-packages\django\db\migrations\loader.py", line 276, in _reraise_missing_dependency
    raise exc
  File "c:\programdata\anaconda3\lib\site-packages\django\db\migrations\loader.py", line 286, in build_graph
    self.graph.add_dependency(migration, key, parent)
  File "c:\programdata\anaconda3\lib\site-packages\django\db\migrations\graph.py", line 126, in add_dependency
    parent
django.db.migrations.exceptions.NodeNotFoundError: Migration wooey.0029_auto_20171211_0145 dependencies reference nonexistent parent node ('wooey', '0028_add_script_subparser')

**Comment by pymenow** [comment]
Tried this on the Linux box where I had originally run into the bug and I still see the same error : 
Converting ../test.py
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/anaconda/anaconda3/lib/python3.6/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/opt/anaconda/anaconda3/lib/python3.6/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/anaconda/anaconda3/lib/python3.6/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/anaconda/anaconda3/lib/python3.6/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/opt/anaconda/anaconda3/lib/python3.6/site-packages/wooey/management/commands/addscript.py", line 73, in handle
    res = add_wooey_script(**add_kwargs)
  File "/opt/anaconda/anaconda3/lib/python3.6/site-packages/wooey/backend/utils.py", line 309, in add_wooey_script
    param_group_name = param_group_info.get('group')
AttributeError: 'str' object has no attribute 'get'

**Comment by pymenow** [comment]
This was a permission error on my end. Its fixed on my Linux box now with wooey-0.9.10.
I need to still sort the issues out on my windows box ...will try to clean up anaconda in windows .

**Comment by Chris7** [comment]
It's because a migration slipped in on branch change that wasn't on git control. I'll push a quick fix :(

**Comment by pymenow** [comment]
@Chris7  great, looking forward to it.
