### ISSUE TITLE
Jobs stuck on 'waiting' on Windows

### ISSUE THREAD

**Issue by luisdelatorre012** [wooey/Wooey#218]
I'm trying to use Wooey on Windows. I'm running Wooey through a Procfile containing

```
web:  python manage.py runserver
worker: python manage.py celery worker -c 1 -l info
EOM
```

When I submit a job, the results page is stuck on 'Waiting' and nothing loads in the console.

I'm getting a constant stream of output from the console that I've included below.

This repeats indefinitely, with the worker name changing from `Worker 1` to `Worker n` for various n.

```
C:\Users\chq-k2einstall\AppData\Local\Continuum\miniconda3\envs\wooey\lib\site-p
ackages\celery\apps\worker.py:161: CDeprecationWarning:
Starting from version 3.2 Celery will refuse to accept pickle by default.

The pickle serializer is a security concern as it may give attackers
the ability to execute any command.  It's important to secure
your broker from unauthorized access when using pickle, so we think
that enabling pickle should require a deliberate action and not be
the default choice.

If you depend on pickle then you should set a setting to disable this
warning and to be sure that everything will continue working
when you upgrade to Celery 3.2::

    CELERY_ACCEPT_CONTENT = ['pickle', 'json', 'msgpack', 'yaml']

You must only enable the serializers that you will actually use.


  warnings.warn(CDeprecationWarning(W_PICKLE_DEPRECATED))

[2018-03-06 16:01:50,366: WARNING/MainProcess] C:\Users\chq-k2einstall\AppData\L
ocal\Continuum\miniconda3\envs\wooey\lib\site-packages\celery\apps\worker.py:161
: CDeprecationWarning:
Starting from version 3.2 Celery will refuse to accept pickle by default.

The pickle serializer is a security concern as it may give attackers
the ability to execute any command.  It's important to secure
your broker from unauthorized access when using pickle, so we think
that enabling pickle should require a deliberate action and not be
the default choice.

If you depend on pickle then you should set a setting to disable this
warning and to be sure that everything will continue working
when you upgrade to Celery 3.2::

    CELERY_ACCEPT_CONTENT = ['pickle', 'json', 'msgpack', 'yaml']

You must only enable the serializers that you will actually use.


  warnings.warn(CDeprecationWarning(W_PICKLE_DEPRECATED))


 -------------- celery@chq-llama-de3 v3.1.25 (Cipater)
---- **** -----
--- * ***  * -- Windows-2012ServerR2-6.3.9600-SP0
-- * - **** ---
- ** ---------- [config]
- ** ---------- .> app:         default:0x7a3b67d630 (.default.Loader)
- ** ---------- .> transport:   django://localhost//
- ** ---------- .> results:
- *** --- * --- .> concurrency: 1 (prefork)
-- ******* ----
--- ***** ----- [queues]
 -------------- .> celery           exchange=celery(direct) key=celery


[tasks]
  . CogSolver.wooey_celery_app.debug_task
  . wooey.tasks.WooeyTask
  . wooey.tasks.cleanup_wooey_jobs
  . wooey.tasks.submit_script

[2018-03-06 16:01:50,678: INFO/MainProcess] Connected to django://localhost//
[2018-03-06 16:01:50,709: WARNING/MainProcess] celery@chq-llama-de3 ready.
[2018-03-06 16:01:51,320: INFO/Worker-1] child process 15744 calling self.run()
[2018-03-06 16:01:51,526: ERROR/Worker-1] Process Worker-1
Traceback (most recent call last):
  File "C:\Users\chq-k2einstall\AppData\Local\Continuum\miniconda3\envs\wooey\li
b\site-packages\kombu\utils\__init__.py", line 323, in __get__
    return obj.__dict__[self.__name__]
KeyError: 'backend'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\chq-k2einstall\AppData\Local\Continuum\miniconda3\envs\wooey\li
b\site-packages\billiard\process.py", line 292, in _bootstrap
    self.run()
  File "C:\Users\chq-k2einstall\AppData\Local\Continuum\miniconda3\envs\wooey\li
b\site-packages\billiard\pool.py", line 292, in run
    self.after_fork()
  File "C:\Users\chq-k2einstall\AppData\Local\Continuum\miniconda3\envs\wooey\li
b\site-packages\billiard\pool.py", line 395, in after_fork
    self.initializer(*self.initargs)
  File "C:\Users\chq-k2einstall\AppData\Local\Continuum\miniconda3\envs\wooey\li
b\site-packages\celery\concurrency\prefork.py", line 81, in process_initializer
    app=app)
  File "C:\Users\chq-k2einstall\AppData\Local\Continuum\miniconda3\envs\wooey\li
b\site-packages\celery\app\trace.py", line 161, in build_tracer
    backend = task.backend
  File "C:\Users\chq-k2einstall\AppData\Local\Continuum\miniconda3\envs\wooey\li
b\site-packages\celery\app\task.py", line 938, in backend
    return self.app.backend
  File "C:\Users\chq-k2einstall\AppData\Local\Continuum\miniconda3\envs\wooey\li
b\site-packages\kombu\utils\__init__.py", line 325, in __get__
    value = obj.__dict__[self.__name__] = self.__get(obj)
  File "C:\Users\chq-k2einstall\AppData\Local\Continuum\miniconda3\envs\wooey\li
b\site-packages\celery\app\base.py", line 634, in backend
    return self._get_backend()
  File "C:\Users\chq-k2einstall\AppData\Local\Continuum\miniconda3\envs\wooey\li
b\site-packages\celery\app\base.py", line 444, in _get_backend
    self.loader)
  File "C:\Users\chq-k2einstall\AppData\Local\Continuum\miniconda3\envs\wooey\li
b\site-packages\celery\backends\__init__.py", line 68, in get_backend_by_url
    return get_backend_cls(backend, loader), url
  File "C:\Users\chq-k2einstall\AppData\Local\Continuum\miniconda3\envs\wooey\li
b\site-packages\celery\backends\__init__.py", line 49, in get_backend_cls
    cls = symbol_by_name(backend, aliases)
  File "C:\Users\chq-k2einstall\AppData\Local\Continuum\miniconda3\envs\wooey\li
b\site-packages\kombu\utils\__init__.py", line 96, in symbol_by_name
    module = imp(module_name, package=package, **kwargs)
  File "C:\Users\chq-k2einstall\AppData\Local\Continuum\miniconda3\envs\wooey\li
b\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\chq-k2einstall\AppData\Local\Continuum\miniconda3\envs\wooey\li
b\site-packages\djcelery\backends\database.py", line 11, in <module>
    from ..models import TaskMeta, TaskSetMeta
  File "C:\Users\chq-k2einstall\AppData\Local\Continuum\miniconda3\envs\wooey\li
b\site-packages\djcelery\models.py", line 30, in <module>
    class TaskMeta(models.Model):
  File "C:\Users\chq-k2einstall\AppData\Local\Continuum\miniconda3\envs\wooey\li
b\site-packages\django\db\models\base.py", line 94, in __new__
    app_config = apps.get_containing_app_config(module)
  File "C:\Users\chq-k2einstall\AppData\Local\Continuum\miniconda3\envs\wooey\li
b\site-packages\django\apps\registry.py", line 239, in get_containing_app_config

    self.check_apps_ready()
  File "C:\Users\chq-k2einstall\AppData\Local\Continuum\miniconda3\envs\wooey\li
b\site-packages\django\apps\registry.py", line 124, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.
[2018-03-06 16:01:51,526: ERROR/Worker-1] Process Worker-1
Traceback (most recent call last):
  File "C:\Users\chq-k2einstall\AppData\Local\Continuum\miniconda3\envs\wooey\li
b\site-packages\kombu\utils\__init__.py", line 323, in __get__
    return obj.__dict__[self.__name__]
KeyError: 'backend'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\chq-k2einstall\AppData\Local\Continuum\miniconda3\envs\wooey\li
b\site-packages\billiard\process.py", line 292, in _bootstrap
    self.run()
  File "C:\Users\chq-k2einstall\AppData\Local\Continuum\miniconda3\envs\wooey\li
b\site-packages\billiard\pool.py", line 292, in run
    self.after_fork()
  File "C:\Users\chq-k2einstall\AppData\Local\Continuum\miniconda3\envs\wooey\li
b\site-packages\billiard\pool.py", line 395, in after_fork
    self.initializer(*self.initargs)
  File "C:\Users\chq-k2einstall\AppData\Local\Continuum\miniconda3\envs\wooey\li
b\site-packages\celery\concurrency\prefork.py", line 81, in process_initializer
    app=app)
  File "C:\Users\chq-k2einstall\AppData\Local\Continuum\miniconda3\envs\wooey\li
b\site-packages\celery\app\trace.py", line 161, in build_tracer
    backend = task.backend
  File "C:\Users\chq-k2einstall\AppData\Local\Continuum\miniconda3\envs\wooey\li
b\site-packages\celery\app\task.py", line 938, in backend
    return self.app.backend
  File "C:\Users\chq-k2einstall\AppData\Local\Continuum\miniconda3\envs\wooey\li
b\site-packages\kombu\utils\__init__.py", line 325, in __get__
    value = obj.__dict__[self.__name__] = self.__get(obj)
  File "C:\Users\chq-k2einstall\AppData\Local\Continuum\miniconda3\envs\wooey\li
b\site-packages\celery\app\base.py", line 634, in backend
    return self._get_backend()
  File "C:\Users\chq-k2einstall\AppData\Local\Continuum\miniconda3\envs\wooey\li
b\site-packages\celery\app\base.py", line 444, in _get_backend
    self.loader)
  File "C:\Users\chq-k2einstall\AppData\Local\Continuum\miniconda3\envs\wooey\li
b\site-packages\celery\backends\__init__.py", line 68, in get_backend_by_url
    return get_backend_cls(backend, loader), url
  File "C:\Users\chq-k2einstall\AppData\Local\Continuum\miniconda3\envs\wooey\li
b\site-packages\celery\backends\__init__.py", line 49, in get_backend_cls
    cls = symbol_by_name(backend, aliases)
  File "C:\Users\chq-k2einstall\AppData\Local\Continuum\miniconda3\envs\wooey\li
b\site-packages\kombu\utils\__init__.py", line 96, in symbol_by_name
    module = imp(module_name, package=package, **kwargs)
  File "C:\Users\chq-k2einstall\AppData\Local\Continuum\miniconda3\envs\wooey\li
b\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\chq-k2einstall\AppData\Local\Continuum\miniconda3\envs\wooey\li
b\site-packages\djcelery\backends\database.py", line 11, in <module>
    from ..models import TaskMeta, TaskSetMeta
  File "C:\Users\chq-k2einstall\AppData\Local\Continuum\miniconda3\envs\wooey\li
b\site-packages\djcelery\models.py", line 30, in <module>
    class TaskMeta(models.Model):
  File "C:\Users\chq-k2einstall\AppData\Local\Continuum\miniconda3\envs\wooey\li
b\site-packages\django\db\models\base.py", line 94, in __new__
    app_config = apps.get_containing_app_config(module)
  File "C:\Users\chq-k2einstall\AppData\Local\Continuum\miniconda3\envs\wooey\li
b\site-packages\django\apps\registry.py", line 239, in get_containing_app_config

    self.check_apps_ready()
  File "C:\Users\chq-k2einstall\AppData\Local\Continuum\miniconda3\envs\wooey\li
b\site-packages\django\apps\registry.py", line 124, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.
[2018-03-06 16:01:51,664: ERROR/MainProcess] Process 'Worker-1' pid:15744 exited
 with 'exitcode 1'
```

**Comment by luisdelatorre012** [comment]
Some more details: I'm on Windows 8, python 3.6.4, django 1.9.3. This problem happens when I use the  [example script](http://wooey.readthedocs.io/en/latest/scripts.html) in the documentation.

Also, this seems related to [issue 138](https://github.com/wooey/Wooey/issues/138).

**Comment by Chris7** [comment]
I think the problem is this:
```
   self.check_apps_ready()
  File "C:\Users\chq-k2einstall\AppData\Local\Continuum\miniconda3\envs\wooey\li
b\site-packages\django\apps\registry.py", line 124, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.
```
Can you provide your settings?

**Comment by luisdelatorre012** [comment]
I'm not sure which settings you're asking for.

I put django_settings.py, wooey_settings.py, and user_settings.py on [gist](https://gist.github.com/luisdelatorre012/04d778afd6fe1fb8b14365492fa5ccb5)

**Comment by luisdelatorre012** [comment]
I've compared the settings files for a working installation of wooey (also django 1.9, but on linux), and the files are identical. Looking at Stackoverflow, questions asking about `django.core.exceptions.AppRegistryNotReady` suggest running `python manage.py check` uncovers problems. That returns `System check identified no issues (0 silenced).`

**Comment by Chris7** [comment]
It looks like the problem is that kombu has removed the `django` transport backend. You'll need to change the settings to a custom broker (like rabbit or redis) and a real backend (like redis). This will need to be adressed in the bootstrap script as well.

**Comment by luisdelatorre012** [comment]
Thanks. I don't understand what any of this means, but I'll try to figure it out. Before I do that, is this an issue simply because I'm using Windows, or something more specific my settings/system/configuration?

**Comment by luisdelatorre012** [comment]
I think I'm making some progress, but I'm not sure about this: "This will need to be adressed in the bootstrap script as well." I have no idea what the bootstrap script is. Is there documentation on this?

**Comment by Chris7** [comment]
Hi @luisdelatorre012 , the bootstrap part is a note for me. The bootstrap script is `wooify`, which sets projects up with some defaults. The defaults aren't meant for a production instance, so you would need to have a real backend/broker to expand past a simple site.

What you need to do is to 1) setup a real backend like redis and 2) setup a real broker like rabbit. You can find out more about them on celery's documentation.

**Comment by luisdelatorre012** [comment]
Should this be closed, since it's not really a wooey issue? (I'd love to explain how I successfully set up a real backend and broker on Windows to help others, but I'm in over my head and am giving up on this for now).

**Comment by Chris7** [comment]
I just put together a set of PRs that addresses this for a demo windows environment: https://github.com/wooey/Wooey/pull/225 and https://github.com/wooey/Wooey/pull/226

It's only on master, which needs some cleanup with migrations (so I wouldn't move anything you want to keep around off master at the moment), but you should be able to get a working demo off `wooify` with the latest on master now.
