### ISSUE TITLE
job_id = kwargs.pop('wooey_job') keyerror: wooey_job

### ISSUE THREAD

**Issue by carlsunderman** [wooey/Wooey#272]
have gotten this error with python 3.x and 2.x on a new install using the sample script on multiple machines.

**Comment by carlsunderman** [comment]
have gotten this error with python 3.x on a new install using the sample script on multiple machines.

**Comment by carlsunderman** [comment]
[2019-02-22 15:39:53,981: INFO/MainProcess] Received task: wooey.tasks.submit_script[be4c78dd-a754-40e1-a2a3-55ceace64d18]
[2019-02-22 15:39:53,992: ERROR/MainProcess] Pool callback raised exception: KeyError('wooey_job',)
Traceback (most recent call last):
  File "d:\programdata\anaconda3\envs\py36\lib\site-packages\django\db\models\query.py", line 464, in get_or_create
    return self.get(**lookup), False
  File "d:\programdata\anaconda3\envs\py36\lib\site-packages\django\db\models\query.py", line 380, in get
    self.model._meta.object_name
django_celery_results.models.DoesNotExist: TaskResult matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\programdata\anaconda3\envs\py36\lib\site-packages\billiard\pool.py", line 1747, in safe_apply_callback
    fun(*args, **kwargs)
  File "d:\programdata\anaconda3\envs\py36\lib\site-packages\celery\worker\request.py", line 367, in on_failure
    self.id, exc, request=self, store_result=self.store_errors,
  File "d:\programdata\anaconda3\envs\py36\lib\site-packages\celery\backends\base.py", line 157, in mark_as_failure
    traceback=traceback, request=request)
  File "d:\programdata\anaconda3\envs\py36\lib\site-packages\celery\backends\base.py", line 322, in store_result
    request=request, **kwargs)
  File "d:\programdata\anaconda3\envs\py36\lib\site-packages\django_celery_results\backends\database.py", line 35, in _store_result
    task_kwargs=task_kwargs,
  File "d:\programdata\anaconda3\envs\py36\lib\site-packages\django_celery_results\managers.py", line 50, in _inner
    return fun(*args, **kwargs)
  File "d:\programdata\anaconda3\envs\py36\lib\site-packages\django_celery_results\managers.py", line 126, in store_result
    obj, created = self.get_or_create(task_id=task_id, defaults=fields)
  File "d:\programdata\anaconda3\envs\py36\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "d:\programdata\anaconda3\envs\py36\lib\site-packages\django\db\models\query.py", line 466, in get_or_create
    return self._create_object_from_params(lookup, params)
  File "d:\programdata\anaconda3\envs\py36\lib\site-packages\django\db\models\query.py", line 499, in _create_object_from_params
    params = {k: v() if callable(v) else v for k, v in params.items()}
  File "d:\programdata\anaconda3\envs\py36\lib\site-packages\django\db\models\query.py", line 499, in <dictcomp>
    params = {k: v() if callable(v) else v for k, v in params.items()}
  File "d:\programdata\anaconda3\envs\py36\lib\site-packages\celery\app\trace.py", line 642, in __protected_call__
    return orig(self, *args, **kwargs)
  File "d:\programdata\anaconda3\envs\py36\lib\site-packages\celery\app\task.py", line 375, in __call__
    return self.run(*args, **kwargs)
  File "d:\programdata\anaconda3\envs\py36\lib\site-packages\wooey\tasks.py", line 79, in submit_script
    job_id = kwargs.pop('wooey_job')
KeyError: 'wooey_job'

**Comment by Chris7** [comment]
Could you paste the output of `pip freeze` and how you are setting up wooey?

**Comment by carlsunderman** [comment]
here is pip freeze from my python 3.6 env 

aiohttp==3.4.4
alabaster==0.7.11
amqp==2.4.1
appdirs==1.4.3
asn1crypto==0.24.0
astroid==2.0.4
async-timeout==3.0.1
attrs==18.2.0
Automat==0.7.0
autopep8==1.4.3
Babel==2.6.0
backcall==0.1.0
billiard==3.5.0.5
bleach==2.1.4
bokeh==1.0.1
celery==4.2.1
certifi==2018.11.29
cffi==1.11.5
chardet==3.0.4
Click==7.0
clinto==0.3.0
cloudpickle==0.5.5
colorama==0.3.9
constantly==15.1.0
cryptography==2.4.2
cycler==0.10.0
cytoolz==0.9.0.1
dask==0.20.0
decorator==4.3.0
distributed==1.24.0
Django==1.11.20
django-autoslug==1.9.4
django-celery-results==1.0.4
django-crispy-forms==1.7.2
dnspython==1.16.0
docutils==0.14
entrypoints==0.2.3
eventlet==0.24.1
greenlet==0.4.15
h5py==2.8.0
heapdict==1.0.0
html5lib==1.0.1
hyperlink==18.0.0
idna==2.7
idna-ssl==1.1.0
imagesize==1.1.0
incremental==17.5.0
ipykernel==4.9.0
ipython==6.5.0
ipython-genutils==0.2.0
ipywidgets==7.4.1
isort==4.3.4
jedi==0.12.1
Jinja2==2.10
jsonfield==2.0.2
jsonschema==2.6.0
jupyter==1.0.0
jupyter-client==5.2.3
jupyter-console==5.2.0
jupyter-core==4.4.0
keyring==13.2.1
kiwisolver==1.0.1
kombu==4.3.0
lazy-object-proxy==1.3.1
locket==0.2.0
MarkupSafe==1.0
matplotlib==3.0.0
mccabe==0.6.1
mistune==0.8.3
mkl-fft==1.0.6
mkl-random==1.0.1
monotonic==1.5
msgpack==0.5.6
multidict==4.4.2
mygeotab==0.8.0
nbconvert==5.3.1
nbformat==4.4.0
notebook==5.6.0
numpy==1.15.2
numpydoc==0.8.0
olefile==0.46
packaging==17.1
pandas==0.23.4
pandocfilters==1.4.2
parso==0.3.1
partd==0.3.9
pickleshare==0.7.4
Pillow==5.3.0
plotly==3.4.0
pprint==0.1
prometheus-client==0.3.1
prompt-toolkit==1.0.15
psutil==5.4.7
pyasn1==0.4.4
pyasn1-modules==0.2.2
pycodestyle==2.4.0
pycparser==2.18
pyflakes==2.0.0
Pygments==2.2.0
pylint==2.1.1
pymongo==3.7.2
pyOpenSSL==18.0.0
pyparsing==2.2.0
pypiwin32==223
PySocks==1.6.8
python-dateutil==2.7.3
pytz==2018.5
pywin32==223
pywinpty==0.5.4
PyYAML==3.13
pyzmq==17.1.2
QtAwesome==0.4.4
qtconsole==4.4.1
QtPy==1.5.0
requests==2.19.1
retrying==1.3.3
rope==0.11.0
scipy==1.1.0
Send2Trash==1.5.0
service-identity==17.0.0
simplegeneric==0.8.1
six==1.11.0
snowballstemmer==1.2.1
sortedcontainers==2.0.5
Sphinx==1.7.9
sphinxcontrib-websupport==1.1.0
spyder==3.3.1
spyder-kernels==0.2.6
tblib==1.3.2
terminado==0.8.1
testpath==0.3.1
toolz==0.9.0
tornado==5.1
traitlets==4.3.2
Twisted==18.7.0
typed-ast==1.1.0
urllib3==1.23
vine==1.2.0
wcwidth==0.1.7
webencodings==0.5.1
widgetsnbextension==3.4.1
win-inet-pton==1.0.1
wincertstore==0.2
wooey==0.10.1
wrapt==1.10.11
yarl==1.2.6
zict==0.1.3
zope.interface==4.5.0

I set it up via the instructions. installed with pip then 
wooify -p <project>

i did notice that setting celery to false in settings, it worked, in both environments.

i launched celery per the upgrade instructions

celery -A <project> worker -l info

**Comment by Chris7** [comment]
It looks like the kombu filesystem broker is at fault. I'll see if there's a way to salvage it at all. Otherwise, setting up a real broker will resolve this problem (like rabbit). You can see these settings in `your_project/settings/user_settings.py` with `CELERY_BROKER_URL`

**Comment by Chris7** [comment]
Ah, it's realted to this issue: https://github.com/celery/celery/issues/4081. Can you set FORKED_BY_MULTIPROCESSING=1 as an environment variable?

**Comment by Chris7** [comment]
Additionally, there is this bit about running on windows in the docs:
```
On Windows, the --beat option may not be supported and the eventlet pool will need to be specified. This looks like:
```

Honestly, this problem has come up enough that I need to make that more visible -- any suggestions?

**Comment by carlsunderman** [comment]
Chris7,

yes, it seems to be working now. 
I launched celery as you said, using eventlet and modified  wooey_celery_app.py, adding 
os.environ.setdefault('FORKED_BY_MULTIPROCESSING', '1')
before importing celery from:
> Ah, it's realted to this issue: [celery/celery#4081](https://github.com/celery/celery/issues/4081). Can you set FORKED_BY_MULTIPROCESSING=1 as an environment variable?

thank you very much
