### ISSUE TITLE
celery error

### ISSUE THREAD

**Issue by razermouse** [wooey/Wooey#279]
I'm not sure of the consequence, but I see the following error for "wooey.tasks.cleanup_dead_jobs" in celery:

[2019-05-31 01:30:00,092: INFO/Beat] Scheduler: Sending due task cleanup-dead-jobs (wooey.tasks.cleanup_dead_jobs)
[2019-05-31 01:30:00,281: INFO/MainProcess] Received task: wooey.tasks.cleanup_dead_jobs[666601a4-a092-437b-8bfd-7f469ad07bff]
[2019-05-31 01:30:01,300: ERROR/ForkPoolWorker-2] Task wooey.tasks.cleanup_dead_jobs[666601a4-a092-437b-8bfd-7f469ad07bff] raised unexpected: AttributeError("'NoneType' object has no attribute 'iteritems'",)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery-4.3.0-py2.7.egg/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery-4.3.0-py2.7.egg/celery/app/trace.py", line 648, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/ubuntu/Wooey/wooey/tasks.py", line 237, in cleanup_dead_jobs
    active_tasks = {task['id'] for worker, tasks in six.iteritems(inspect.active()) for task in tasks}
  File "/home/ubuntu/.local/lib/python2.7/site-packages/six.py", line 605, in iteritems
    return d.iteritems(**kw)
AttributeError: 'NoneType' object has no attribute 'iteritems'

**Comment by Chris7** [comment]
This is related to #277 and a PR is in to fix
