### ISSUE TITLE
while true script fail to stop

### ISSUE THREAD

**Issue by etiaxie** [wooey/Wooey#305]
i  add a while true script into wooey like this:
def main():
    args = parser.parse_args()
    for i in range(99):
        print i
        time.sleep(10)

and this script can't be stoppd and i can see error in celery:
[2019-12-06 11:45:17,920: ERROR/MainProcess] pidbox command error: AttributeError("'module' object has no attribute 'SIGKILL'",)
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\kombu\pidbox.py", line 105, in dispatch
    reply = handle(method, kwdict(arguments))
  File "C:\Python27\lib\site-packages\kombu\pidbox.py", line 126, in handle_cast
    return self.handle(method, arguments)
  File "C:\Python27\lib\site-packages\kombu\pidbox.py", line 120, in handle
    return self.handlers[method](self.state, **arguments)
  File "C:\Python27\lib\site-packages\celery\worker\control.py", line 82, in revoke
    signum = _signals.signum(signal or 'TERM')
  File "C:\Python27\lib\site-packages\celery\platforms.py", line 670, in signum
    return getattr(_signal, signal_name)
AttributeError: 'module' object has no attribute 'SIGKILL'

does it cause by wooey&django version? 
my version: 
wooey (0.9.11)
Django (1.8)
django-autoslug (1.9.3)
django-celery (3.2.2)
django-grappelli (2.8.1)

**Comment by Chris7** [comment]
I think this is an issue with the version of celery/billard (https://github.com/celery/billiard/issues/135). What does pip freeze provide?
