### ISSUE TITLE
manage.py addscript giving confusing output

### ISSUE THREAD

**Issue by CatherineH** [wooey/Wooey#44]
I'm trying to add the script ~/testing_scripts/scripts/WooeyScript.py to my wooey project, but there seems to be a problem with my argparser, but I don't understand the error that it is producing:

```
cholloway@nb-cholloway:~/Wooey/testing_scripts$ ./manage.py addscript ~/testing_scripts/scripts/WooeyScript.py 
Converting /home/cholloway/testing_scripts/scripts/WooeyScript.py
usage: manage.py [-h] [--data_topics DATA_TOPICS [DATA_TOPICS ...]]
                 [--labels LABELS [LABELS ...]] [--foldername [FOLDERNAME]]
                 [--filename [FILENAME]] [--vicon_topic [VICON_TOPIC]]
                 [--results_file [RESULTS_FILE]] [--heatmap [HEATMAP]]
                 [--sql [SQL]] [--from_csv [FROM_CSV]]
                 [--output_foldername [OUTPUT_FOLDERNAME]]
manage.py: error: unrecognized arguments: addscript /home/cholloway/testing_scripts/scripts/WooeyScript.py
Error while loading /home/cholloway/Wooey/testing_scripts/testing_scripts/user_uploads/wooey_scripts/WooeyScript_PNgGIQt.py:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/clinto-0.1.1-py2.7.egg/clinto/parser.py", line 171, in __init__
    module = imp.load_source(script_name, script_path)
  File "/home/cholloway/Wooey/testing_scripts/testing_scripts/user_uploads/wooey_scripts/WooeyScript_PNgGIQt.py", line 24, in <module>
    args = parser.parse_args()
  File "/usr/lib/python2.7/argparse.py", line 1693, in parse_args
    self.error(msg % ' '.join(argv))
  File "/usr/lib/python2.7/argparse.py", line 2363, in error
    self.exit(2, _('%s: error: %s\n') % (self.prog, message))
  File "/usr/lib/python2.7/argparse.py", line 2351, in exit
    _sys.exit(status)
SystemExit: 2

usage: manage.py [-h] [--data_topics DATA_TOPICS [DATA_TOPICS ...]]
                 [--labels LABELS [LABELS ...]] [--foldername [FOLDERNAME]]
                 [--filename [FILENAME]] [--vicon_topic [VICON_TOPIC]]
                 [--results_file [RESULTS_FILE]] [--heatmap [HEATMAP]]
                 [--sql [SQL]] [--from_csv [FROM_CSV]]
                 [--output_foldername [OUTPUT_FOLDERNAME]]
manage.py: error: unrecognized arguments: addscript /home/cholloway/testing_scripts/scripts/WooeyScript.py
Error while loading /home/cholloway/Wooey/testing_scripts/testing_scripts/user_uploads/wooey_scripts/WooeyScript_PNgGIQt.py:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/clinto-0.1.1-py2.7.egg/clinto/parser.py", line 171, in __init__
    module = imp.load_source(script_name, script_path)
  File "/home/cholloway/Wooey/testing_scripts/testing_scripts/user_uploads/wooey_scripts/WooeyScript_PNgGIQt.py", line 24, in <module>
    args = parser.parse_args()
  File "/usr/lib/python2.7/argparse.py", line 1693, in parse_args
    self.error(msg % ' '.join(argv))
  File "/usr/lib/python2.7/argparse.py", line 2363, in error
    self.exit(2, _('%s: error: %s\n') % (self.prog, message))
  File "/usr/lib/python2.7/argparse.py", line 2351, in exit
    _sys.exit(status)
SystemExit: 2

Converted 1 scripts
```

Is this the correct way to use addscript?

**Comment by Chris7** [comment]
Hey @CatherineH. It looks like argparse itself it throwing an error, meaning there may be some issue with your script or because Wooey is moving your script's location. Could you put your script online as a gist so I can look at it? If it's sensitive information, I can help over email as well.

**Comment by CatherineH** [comment]
hey @Chris7, thanks for responding. Here's my gist - I hope it helps:

https://gist.github.com/CatherineH/6d90247cf1faa4eb1a76

**Comment by Chris7** [comment]
Hey @CatherineH. There are two issues here.

1) It looks like it's because you are defining your type as list, clinto is failing. My experience with lists in argparse is to create lists by using the nargs='+' or '*' with the type keyword being the datatype of the list components.  I don't know if the type=list is valid argparse at the moment as well, but will need to look into that. That being said, it shouldn't break like that and will have to be fixed in clinto to at least provide a more informative error.

2) The second reason it is failing is because you are parsing your arguments outside of a function or the __main__ statement. You should do args = parser.parse_args() in your __main__ statement. Because python is loading the code as a library to inspect its elements and figure out what components there are, the parse_args() is being executed and consequentially, failing because it isn't being executed from the command line.

Thanks for creating this issue and putting your code online to inspect further. I hope this makes sense and helps your resolve and get Wooey working. If not, just let me know.

**Comment by CatherineH** [comment]
I'm still having trouble.

So, if I stick everything in main, the addscript seems to work fine, but when I go to the actual script in the wooey web interface, I can't see any of my parameters. 

About a month ago, when wooey and djanguify were two separate projects, I had a script that worked and generated the form for the parameters as I would expect. It looked like this:

```
import argparse

parser = argparse.ArgumentParser(description="Plot Velocity Controller error histograms")
parser.add_argument("-f", "--filename", dest="filename", default='../data/velocity_tester/pelican/z position/z_1.0_limit_2015-05-29-10-17-14.bag',
                  help="name of the file to plot graph for")
parser.add_argument("-c", "--component", dest="component", default='z', help="Component to analyze")
parser.add_argument("-n","--uav_number", dest="uav_number", default=5, help="UAV number to analyze")

args = parser.parse_args()

print "Got "+args.filename+" with component: "+args.component+" uav number: "+str(args.uav_number)
```

However, this gives me the same error as before when I try to add it:

```
cholloway@nb-cholloway:~/Wooey/testing_scripts$ ./manage.py addscript histogram_minimal.py 
Converting histogram_minimal.py
usage: manage.py [-h] [-f FILENAME] [-c COMPONENT] [-n UAV_NUMBER]
manage.py: error: unrecognized arguments: addscript histogram_minimal.py
Error while loading /home/cholloway/Wooey/testing_scripts/testing_scripts/user_uploads/wooey_scripts/histogram_minimal_jgS9oK3.py:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/clinto-0.1.1-py2.7.egg/clinto/parser.py", line 171, in __init__
    module = imp.load_source(script_name, script_path)
  File "/home/cholloway/Wooey/testing_scripts/testing_scripts/user_uploads/wooey_scripts/histogram_minimal_jgS9oK3.py", line 13, in <module>
    args = parser.parse_args()
  File "/usr/lib/python2.7/argparse.py", line 1693, in parse_args
    self.error(msg % ' '.join(argv))
  File "/usr/lib/python2.7/argparse.py", line 2363, in error
    self.exit(2, _('%s: error: %s\n') % (self.prog, message))
  File "/usr/lib/python2.7/argparse.py", line 2351, in exit
    _sys.exit(status)
SystemExit: 2

usage: manage.py [-h] [-f FILENAME] [-c COMPONENT] [-n UAV_NUMBER]
manage.py: error: unrecognized arguments: addscript histogram_minimal.py
Error while loading /home/cholloway/Wooey/testing_scripts/testing_scripts/user_uploads/wooey_scripts/histogram_minimal_jgS9oK3.py:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/clinto-0.1.1-py2.7.egg/clinto/parser.py", line 171, in __init__
    module = imp.load_source(script_name, script_path)
  File "/home/cholloway/Wooey/testing_scripts/testing_scripts/user_uploads/wooey_scripts/histogram_minimal_jgS9oK3.py", line 13, in <module>
    args = parser.parse_args()
  File "/usr/lib/python2.7/argparse.py", line 1693, in parse_args
    self.error(msg % ' '.join(argv))
  File "/usr/lib/python2.7/argparse.py", line 2363, in error
    self.exit(2, _('%s: error: %s\n') % (self.prog, message))
  File "/usr/lib/python2.7/argparse.py", line 2351, in exit
    _sys.exit(status)
SystemExit: 2

Converted 1 scripts
```

Do you have example scripts to test against? I'm not sure if something is wrong in my install.

**Comment by CatherineH** [comment]
Okay, I think I've figured it out - 

issue 1, the argparser problem that I started with, is caused by having both the argparser and the parser.parse_args() defined in global scope. For example, this script works:

```
import argparse
import sys

parser = argparse.ArgumentParser(description='testing wooey.')
parser.add_argument('--arg1', type=str, default="bloop", help='argument 1')
parser.add_argument('--arg2', help='argument 1', type=str, default="bloop")
parser.add_argument('--arg3', help='argument 1', type=str, default="bloop")

def main():
    args = parser.parse_args()
    print(vars(args))

if __name__ == "__main__":
    sys.exit(main())
```

So does this script:

```
import argparse

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='testing wooey.')
    parser.add_argument('--arg1', type=str, default="bloop", help='argument 1')
    parser.add_argument('--arg2', help='argument 1', type=str, default="bloop") 
    parser.add_argument('--arg3', help='argument 1', type=str, default="bloop")

    args = parser.parse_args()
    print(vars(args))
```

but this one does not:

```
import argparse

parser = argparse.ArgumentParser(description='testing wooey.')
parser.add_argument('--arg1', type=str, default="bloop", help='argument 1')
parser.add_argument('--arg2', help='argument 1', type=str, default="bloop")
parser.add_argument('--arg3', help='argument 1', type=str, default="bloop")
args = parser.parse_args()
print(vars(args))
```

which used to work in a previous version of Wooey.

issue #2, the parameters not showing up, is caused by using argument_default=argparse.SUPPRESS in the ArgumentParser constructor. I think that this is an actual issue that should be fixed. I'll create a separate ticket for this issue.

**Comment by mfitzp** [comment]
@CatherineH thanks for working this out. The issue with scope should be fixed with clinto (and so Wooey) shortly via a blunter fallback that is working for some of my trickier scripts (and Python3) which is open as a PR here https://github.com/wooey/clinto/pull/9 if you want to test it out.
