### ISSUE TITLE
project creation fails with invalid version of django

### ISSUE THREAD

**Issue by kyledenison** [wooey/Wooey#97]
When trying to create a wooey project I get the following error,

$ wooify -p ProjectNamell
Traceback (most recent call last):
  File "/usr/local/bin/wooify", line 9, in <module>
    load_entry_point('wooey==0.9.1', 'console_scripts', 'wooify')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 351, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2363, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2088, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/local/lib/python2.7/dist-packages/wooey-0.9.1-py2.7.egg/wooey/__init__.py", line 1, in <module>
    from . import version
  File "/usr/local/lib/python2.7/dist-packages/wooey-0.9.1-py2.7.egg/wooey/version.py", line 5, in <module>
    DJANGO_VERSION = StrictVersion(get_version())
  File "/usr/lib/python2.7/distutils/version.py", line 40, in __init__
    self.parse(vstring)
  File "/usr/lib/python2.7/distutils/version.py", line 107, in parse
    raise ValueError, "invalid version number '%s'" % vstring
ValueError: invalid version number '1.9c1'

Package versions listed below
$ pip show django
---
Name: Django
Version: 1.9c1
Location: /usr/local/lib/python2.7/dist-packages/Django-1.9c1-py2.7.egg
Requires: 

$ pip show wooey
---
Name: wooey
Version: 0.9.1
Location: /usr/local/lib/python2.7/dist-packages/wooey-0.9.1-py2.7.egg
Requires: Django, django-autoslug, django-celery, six, clinto

**Comment by Chris7** [comment]
Thanks for the report. We use strict versioning for parsing django for compatibility. We can probably just go with the major and minor versions though to enable rc builds. You can fix this by installing with pip install Django=1.8.*

**Comment by kyledenison** [comment]
Thanks for the help. That fixed it for me. First time trying to use either wooey or django for any reason.
